(cram
 (alias pkg)
 (applies_to :whole_subtree))

(env
 (_
  (env-vars
   (DUNE_DEBUG_PACKAGE_LOGS 1))))

(cram
 (deps %{bin:git} %{bin:bc})
 (setup_scripts helpers.sh ../git-helpers.sh)
 (applies_to :whole_subtree))

(cram
 (deps %{bin:patch})
 (applies_to build/opam/patch build/opam/opam-package-with-patch fetch/extra-sources))

(cram
 (applies_to fetch/rev-store-lock-linux)
 (enabled_if
  (= %{system} linux))
 (deps %{bin:strace}))

(cram
 (deps %{bin:awk} %{bin:cmp})
 (applies_to fetch/git-repo))

(cram
 (deps %{bin:make})
 (applies_to build/opam/make rule-deps vendor/duniverse vendor/duniverse/non-dune-pkg))

(cram
 (deps %{bin:which})
 (applies_to pkg-deps))

(cram
 (deps %{bin:curl})
 (applies_to
  unavailable-package-source
  lock/compute-checksums-when-missing
  e2e
  dev-tools/ocamlformat
  fetch/source-caching
  fetch/tarball
  lock/pin-depends
  fetch/extra-sources
  broken-symlink-in-dependency
  vendor/duniverse
  vendor/duniverse/non-dune-pkg))

(cram
 (deps %{bin:md5sum})
 (applies_to
  fetch/source-caching
  fetch/extra-sources
  dev-tools/ocamlformat
  dev-tools/ocamlformat
  broken-symlink-in-dependency
  build/install-file-tracking
  build/package-upgrade-cleanup
  vendor/duniverse
  vendor/duniverse/non-dune-pkg))

(cram
 (deps %{bin:tar})
 (applies_to
  fetch/source-caching
  fetch/tarball
  lock/pin-depends
  fetch/extra-sources
  fetch/pkg-extract-fail
  broken-symlink-in-dependency
  build/install-file-tracking
  build/package-upgrade-cleanup
  vendor/duniverse
  vendor/duniverse/non-dune-pkg))

(cram
 (deps %{bin:ocaml_index})
 (applies_to gh10985))

(cram
 (deps %{bin:unzip})
 (applies_to fetch/pkg-extract-fail fetch/zip-extract-fail))

;; disabled for flakiness

(cram
 (enabled_if false)
 (applies_to gh10959))
