Test the dune pkg fetch command for duniverse packages.

Set up a mock repository:

  $ mkrepo

Non-portable lockdir for simpler output:

  $ export DUNE_CONFIG__PORTABLE_LOCK_DIR=disabled

Create a package that uses dune as its build system:

  $ mkpkg dune-pkg 1.0.0 <<EOF
  > build: ["dune" "build" "-p" name "-j" jobs]
  > EOF

Set up workspace with mock repository:

  $ cat >dune-workspace <<EOF
  > (lang dune 3.20)
  > (lock_dir
  >  (path dune.lock)
  >  (repositories mock))
  > (repository
  >  (name mock)
  >  (url "file://$(pwd)/mock-opam-repository"))
  > EOF

Create a project that depends on the dune package:

  $ cat >dune-project <<EOF
  > (lang dune 3.16)
  > (package (name myproj) (depends dune-pkg))
  > EOF

Lock the dependencies:

  $ dune pkg lock
  Solution for dune.lock (1 package)
  dune:
  - dune-pkg.1.0.0

Check that fetch command runs silently when packages have no sources:

  $ dune pkg fetch -v

Now let's test with a package that has an actual source URL.

Create source files for a dune package:

  $ mkdir -p pkg-source
  $ cat >pkg-source/dune-project <<EOF
  > (lang dune 3.16)
  > (package (name mypkg) (allow_empty))
  > EOF
  $ cat >pkg-source/dune <<EOF
  > (library (name mypkg) (public_name mypkg))
  > EOF
  $ cat >pkg-source/mypkg.ml <<EOF
  > let hello = "hello from mypkg"
  > EOF

Create a lock file with a source URL pointing to our local directory:

  $ make_lockdir
  $ make_lockpkg mypkg <<EOF
  > (version 1.0.0)
  > (build (run dune build -p mypkg @install))
  > (source (copy $PWD/pkg-source))
  > EOF

Fetch the package (using -v for one-liner status messages):

  $ dune pkg fetch -v
  Fetching mypkg.1.0.0 to duniverse/mypkg.1.0.0

Verify the package was placed in duniverse/:

  $ ls duniverse/
  dune
  mypkg.1.0.0
  $ ls duniverse/mypkg.1.0.0/
  dune
  dune-project
  mypkg.ml

Fetch again - should skip already-fetched package:

  $ dune pkg fetch -v
  Cached mypkg.1.0.0

The duniverse directory should have the vendored_dirs stanza:

  $ cat duniverse/dune
  ; This directory is managed by dune pkg
  (vendored_dirs *)
  (vendor mypkg.1.0.0 (libraries mypkg))

A .gitignore file is generated to exclude fetched sources by default:

  $ cat duniverse/.gitignore
  # Auto-generated by dune pkg fetch
  # User patches are stored in patches/, not here
  *
  !.gitignore
  !dune

Now test the full workflow: build a project that uses the duniverse library.

First, remove the original source directory to avoid conflict:

  $ rm -rf pkg-source

Create a new project that uses the duniverse library:

  $ cat >dune-project <<EOF
  > (lang dune 3.16)
  > (package (name myproj) (allow_empty))
  > EOF

  $ cat >dune <<EOF
  > (library (name mylib) (libraries mypkg))
  > EOF

  $ cat >mylib.ml <<EOF
  > let greeting = Mypkg.hello
  > EOF

Build the project - it should use the duniverse library, not the .pkg sandbox:

  $ dune build

Verify the library was built correctly:

  $ cat _build/default/mylib.ml
  let greeting = Mypkg.hello

The duniverse library should be built in the main build context (not .pkg):

  $ ls _build/default/duniverse/mypkg.1.0.0/.mypkg.objs/byte/
  mypkg.cmi
  mypkg.cmo
  mypkg.cmt

Verify that the .pkg directory does NOT contain the mypkg build artifacts
(since it's a duniverse package, not an opam sandbox package):

  $ ls _build/default/.pkg/mypkg/target 2>/dev/null || echo "No .pkg build for mypkg (expected)"
  No .pkg build for mypkg (expected)

Test that edits to duniverse packages are picked up:

  $ cat >duniverse/mypkg.1.0.0/mypkg.ml <<EOF
  > let hello = "EDITED: hello from mypkg v2"
  > EOF

Rebuild - the edit should be picked up:

  $ dune build

  $ cat _build/default/duniverse/mypkg.1.0.0/mypkg.ml
  let hello = "EDITED: hello from mypkg v2"

This confirms that duniverse packages fetched via `dune pkg fetch` are:
1. Built in the main context (not .pkg sandbox)
2. Editable - changes are picked up on rebuild
